### ISSUE TITLE
[Compatibility][Forge] Alex's Mobs support

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Azmalent/potion-descriptions#1]
I've been using a mod lately called Alex's Mobs which adds a lot of different mobs into the game and a few potions which can be made from the drops of some of these mobs.

When using your mod alongside this one, the potions added by Alex's Mobs are missing a description. It would be beneficial if they had a description so that it would provide consistency with the rest of the potions added to my modpack.

Here is the curseforge page: https://www.curseforge.com/minecraft/mc-mods/alexs-mobs

I can provide descriptions of what these new potions do if need be.

Thanks!

**Comment by Azmalent** [comment]
Alex's Mobs is now supported in the new version!
