### ISSUE TITLE
Upgrade Aquatic Insomnia Potions Reversed

### ISSUE THREAD

**Issue by IdrisQe** [Azmalent/potion-descriptions#2]
https://github.com/team-abnormals/upgrade-aquatic/issues/254

The Insomnia and Restfulness potions from Upgrade Aquatic have their descriptions reversed.
The Insomnia potion should be the one listed as increasing the insomnia timer and making Phantoms spawn, while the Restfulness potion should be the one that resets the timer. Currently they're displayed wrong, which is incredibly confusing.

**Comment by Azmalent** [comment]
Fixed in the new version.
