### ISSUE TITLE
Incorrect requirements for Reliquary mod

### ISSUE THREAD

**Issue by Zygus42** [Azmalent/potion-descriptions#4]
Even though Reliquary is shown as an optional mod, now that i've added the latest version of reliquary, the game fails to start, with a message that reliquary is the wrong version for the potion descriptions mod.

**Comment by BugmanBugman** [comment]
Have this problem

**Comment by VirtualGaming1** [comment]
should add Botania and it say only support Botania and currently using Botania (Version#)

Using 1.16.5 FML 16.1.13

Have to disable this mod in my modpack now untill get updated

**Comment by Zygus42** [comment]
You can edit the required dependencies in the .jar to match the other mods until the mod is updated.  This has been happening to a number of mods since a recent forge update that changed the way dependencies are actioned.

**Comment by Azmalent** [comment]
Fixed in the new update.
