### ISSUE TITLE
Error version check

### ISSUE THREAD

**Issue by lebanni** [Azmalent/potion-descriptions#5]
potiondescriptions-1.16.3-1.5.2.jar
Botania-1.16.5-416.jar

![potiondescription](https://user-images.githubusercontent.com/2799575/117399550-1958a500-af01-11eb-9608-e71b441125c4.jpg)

**Comment by ffuentesm** [comment]
I am getting the same Error.

**Comment by Azmalent** [comment]
Fixed in 1.3.5.
