### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [Azmalent/potion-descriptions#9]
Are there plans for updating to 1.18 and 1.19? I really like this mod, and it would be great in my modpack. If you don't plan on porting this, I may try it myself, just wanted to check in with you.

**Comment by BeansBeefBroccoli** [comment]
@Azmalent Bump

Sorry to bother you! Is this project still being worked on, or is it dead?

**Comment by Azmalent** [comment]
It's not dead but I am busy with studying atm, so I don't have much time.
If you want you can port it yourself and submit a PR.

**Comment by BeansBeefBroccoli** [comment]
Thanks for the quick response! I think I will try porting this. Good luck studying!

**Comment by xXMolgadoGamer01Xx** [comment]
Sorry to open this again, but, did you succes on porting it to 1.19.2?
